In [2]:
import numpy as np
from numpy.conftest import dtype

arr = np.arange(10)
print(arr.ndim)

1


In [9]:
arrs=np.array([1,2,3,4,5])#这是一维数组
print(arrs)
print(arrs.ndim)

[1 2 3 4 5]
1


In [11]:
arr3=np.array([[1,2],[9,7]])#二维的数组
print(arr3)
print(arr3.ndim)

[[1 2]
 [9 7]]
2


同质性，不同的类型会强制转为统一类型

In [13]:
arr=np.array([1,'hello'])
print(arr)

['1' 'hello']


ndarry的属性常用的

In [14]:
arr=np.array([[1,2],[9,7]])
print(arr.ndim)#维度
print(arr.shape)#数组的形状
print(arr.size)#大小
print(arr.dtype)#类型
print(arr.itemsize)#元素大小
print(arr.nbytes)#占用内存大小
print(arr.T)#数组的转置

2
(2, 2)
4
int64
8
32
[[1 9]
 [2 7]]


## 3.ndarry的数组创建

In [23]:
##基础的创建
lis=[[1,2],[9,7]]
lis2=[1,2]
#arry=np.array(lis)
arr=np.array(lis2)
print(arr)

[1 2]


In [26]:
#预定于数组全0或者全1
arr=np.zeros((3,4),dtype=int)#写的是数组的形状
print(arr)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [27]:
#全1
arr=np.ones((3,4),dtype=float)
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [3]:
#为空  实际使用过程中不推荐使用
arrs=np.empty((3,4))
print(arrs)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 1.16821131e-307]
 [8.34441742e-308 8.90104239e-307 1.33511290e-306 2.89275220e-307]
 [1.78022342e-306 2.22518251e-306 8.01097889e-307 9.50498564e-043]]


In [4]:
arrys1=np.full((3,5),25)
print(arrys1)

[[25 25 25 25 25]
 [25 25 25 25 25]
 [25 25 25 25 25]]


In [5]:
arry2=np.zeros_like(arrys1)
print(arry2)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [6]:
#等差数列
arrs=np.arange(2,8,2)
print(arrs)

[2 4 6]


In [11]:
#等间隔数列
arrs2=np.linspace(0,10,5) #分成5分
print(arrs2)

[ 0.   2.5  5.   7.5 10. ]


In [13]:
#对数间隔操作
arry5=np.logspace(0,4,2,base=2)
print(arry5)

[ 1. 16.]


In [17]:
#单位矩阵的构建
arry11=np.eye(3,4,dtype=int)#这里的3,4不用给小括号，是指定行列的
print(arry11)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [25]:
#对角矩阵的构建,主对角线上展示的数字
arry12=np.diag([1,2,3])
print(arry12)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [35]:
#生成0-1之间的均匀分布的随机数
arry13=np.random.random((3,4))#生成3行四列的意思
print(arry13)

[[0.38690486 0.86662836 0.74692615 0.68876057]
 [0.27012044 0.77791229 0.57842108 0.83008264]
 [0.86684399 0.10841347 0.77433493 0.8056749 ]]


In [33]:
#生成指定范围的随机数也是均匀分布
arry14=np.random.uniform(1,4,size=(3,4))
print(arry14)

[[1.64975686 2.63336993 2.55494312 3.47622746]
 [2.94750403 2.54239405 3.21322534 3.51343194]
 [3.01819392 1.79866172 3.95294686 3.0021631 ]]


In [37]:
#整数的随机
arry15=np.random.randint(3,9,(3,3))
print(arry15)

[[3 3 3]
 [5 6 4]
 [4 3 6]]


In [42]:
#正态分布 生成随机数列-3-3之间，两边小中间大
arry16=np.random.randn(2,3)
print(arry16)

[[-0.63029868 -0.41537925  0.18518669]
 [-0.28947756 -0.21429327  0.47619551]]


In [64]:
#随机种子，主要是确保数组是一样的不随机变动
np.random.seed(10)
narry16=np.random.randint(1,10,(2,3))
print(narry16)

[[5 1 2]
 [1 2 9]]


# 5.索引与切片

In [73]:
arr17=np.random.randint(1,20,10)
print(arr17)
print(arr17[:])
print(arr17[1:3])
print(arr17[arr17>10])#条件找数据
print(arr17[(arr17>18)&(arr17<20)])#多条件进行判断
print(arr17[slice(2,5)])#分割跟索引效果类似

[17 19 17 15 16 18 19 15 17 11]
[17 19 17 15 16 18 19 15 17 11]
[19 17]
[17 19 17 15 16 18 19 15 17 11]
[19 19]
[17 15 16]


In [88]:
#二维数组的索引
arry21=np.random.randint(1,20,(3,4))
print(arry21)
#print(arry21[arry21>15])
print('-'*10)
print(arry21[1,:])#一个控制行数一个控制列数
print(arry21[2][arry21[2]>10])#获取行的数据

[[ 1  8 11 17]
 [ 3  3 13 11]
 [16  1  6 17]]
----------
[ 3  3 13 11]
[16 17]


@是矩阵的乘法，*就是单纯的数组中的对应数据相乘

In [ ]:
#矩阵乘法
a=np.array([[1,2,3],[2,4,5],[4,5,6]])
B=np.array([[1,2,3],[2,4,5],[1,2,3]])
print(a)
print('-'*20)
print(B)
print('-'*30)
print(a@B)


# 2.numpy中的基本数学函数的使用

In [ ]:
#方差是var，标准差是std
方差计算：每个数减去平均值相加的和除以数的个数，计算数据的离散程度

In [101]:
print(np.var([1,2,3]))
print(np.std([1,2,3]))

0.6666666666666666
0.816496580927726


In [102]:
np.random.seed(0)
list1=[44,47,64,67]
print(np.percentile(list1,80))

65.2


In [104]:
#检查所有元素是否都是真
print(np.all([1,5,3,0]))
print(np.any([1,5,3,0]))#是否有一个为真

False
True


In [ ]:
#自定义条件，很容易可以做一些分类
#where(条件，符合的，不符合的)
